name: 'Test & Release'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: 'Test package'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: '22'

            - name: Install
              run: |
                npm install
                npm run dev:prepare

            - name: Lint
              run: |
                npm run lint:es
                npm run lint:types

            - name: Test
              run: npm run test

    release:
        name: 'Release package'
        needs: [ test ]
        runs-on: ubuntu-latest
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]') &&
          !startsWith(github.ref, 'refs/heads/renovate/')

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install
              run: |
                npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISHING_KEY }}
                npm install
                npm run dev:prepare

            - name: Release
              run: npm run release:ci

    bump-version:
        name: 'Bump package version'
        needs: [ test ]
        runs-on: ubuntu-latest
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true &&
          startsWith(github.event.pull_request.head.ref, 'renovate/')

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install
              run: npm install --from-lockfile

            - name: Bump version
              id: bump_version
              run: |
                NEW_VERSION=$(npm version patch -m "chore: bumped package version to %s")
                echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

            - name: Update CHANGELOG.md
              run: |
                echo -e "# $NEW_VERSION\n- Bumped dependencies\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
                git add CHANGELOG.md

            - name: Push changes
              run: |
                git commit --amend --no-edit
                git push origin HEAD:main --follow-tags
