name: 'Test & Release'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Test package'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: |
          npm install
          npm run dev:prepare

      - name: Lint
        run: |
          npm run lint:es
          npm run lint:types

      - name: Test
        run: npm run test

  release:
    name: 'Release package'
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: |
          npm install
          npm run dev:prepare

      - name: Release (Renovate)
        if: startsWith(github.event.head_commit.message, 'chore(deps)')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          NEW_VERSION=$(npm version patch -m "chore: bumped package version to %s")
          echo -e "# $NEW_VERSION\n- Bumped dependencies\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
          
          git add CHANGELOG.md
          git commit --amend --no-edit
          git push origin main --tags
          
          npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISHING_KEY }}
          npm run release:ci

      - name: Release (Manual)
        if: "!startsWith(github.event.head_commit.message, 'chore(deps)')"
        run: |
          npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISHING_KEY }}
          npm run release:ci || true
